name: app
type: 'nodejs:22'
variables:
    env:
        NODE_ENV: 'production'

web:
    commands:
        start: npm run dev
    locations:
        "/":
            http: true
            https: true

