version: '3.8'

services:
  whatsapp-gateway:
    build: .
    container_name: whatsapp-gateway
    ports:
      - "5001:5001"
    volumes:
      - .:/usr/src/app
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
    environment:
      - NODE_ENV=production
    restart: unless-stopped

